### ISSUE TITLE
Lychee does not work on server. Block clicking and block interacting

### ISSUE THREAD

**Issue by BrokenDawn627** [Snownee/Lychee#1]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

1.2.0

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/infinity-fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Lychee 方块点击、交互功能无法在服务端开的服务器使用
且用*代表的任意方块 在进入服务器后只显示为空气
换成其他单独的实体方块也无法使用
但燃烧物品是可用的

**Comment by Snownee** [comment]
我猜可能被修复了
