### ISSUE TITLE
Clicking on Iesnium ore in JEI with Occultism installed causes a crash.

### ISSUE THREAD

**Issue by Cinderheart** [Snownee/Lychee#11]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

Lychee-1.18.1-forge-1.5.2

### Modloader version

Forge:39.0.88

### Modpack info

See description

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

https://github.com/klikli-dev/occultism/issues/665

More info here.

[crash-2022-02-26_15.48.48-client (2).txt](https://github.com/Snownee/Lychee/files/8148730/crash-2022-02-26_15.48.48-client.2.txt)

Crashlog.

**Comment by Snownee** [comment]
What is your recipe?
