### ISSUE TITLE
crash when clicking on items that have lychee recipes within REI

### ISSUE THREAD

**Issue by SattesKrokodil** [Snownee/Lychee#13]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

1.5.1

### Modloader version

fabric_version=0.46.2+1.18

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/tqFyxDvw

### Issue description

title

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
