### ISSUE TITLE
Anvil crashs client

### ISSUE THREAD

**Issue by TheButterbrotMan** [Snownee/Lychee#16]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

2.2.0

### Modloader version

Fabric: Loader 0.13.3 + API 0.48.0+1.18.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://bytebin.lucko.me/0ZE7m6c2vV

### Issue description

So basically when you try to use an anvil (open it), the client is crashing.

**Comment by Snownee** [comment]
Please provide the log file you reproduce with Lychee installed only. I can't reproduce it

**Comment by TheButterbrotMan** [comment]
> https://bytebin.lucko.me/0ZE7m6c2vV

Ops, i ticked it wrong. My bad. Is a modded enviroment, im not able to reproduce it only with Lychee.

**Comment by Snownee** [comment]
do other recipe types work?

**Comment by TheButterbrotMan** [comment]
> do other recipe types work?

Yes

**Comment by Niketats** [comment]
[crash-2022-04-14_20.37.02-client.txt](https://github.com/Snownee/Lychee/files/8491196/crash-2022-04-14_20.37.02-client.txt)
Same, crash when put something in anvil
[latest.log](https://github.com/Snownee/Lychee/files/8491205/latest.log)

**Comment by Snownee** [comment]
[2.2.1.zip](https://github.com/Snownee/Lychee/files/8491483/2.2.1.zip)

does this fix the problem? (please also test with server)

**Comment by TheButterbrotMan** [comment]
Testing it right now!

**Comment by TheButterbrotMan** [comment]
Can confirm is working.

> [2.2.1.zip](https://github.com/Snownee/Lychee/files/8491483/2.2.1.zip)
> 
> does this fix the problem? (please also test with server)

**Comment by Snownee** [comment]
uploaded

**Comment by TheButterbrotMan** [comment]
Hmm, i dont know what to say....

But somehow its back....

https://bytebin.lucko.me/ATl3ZLB1AZ

**Comment by Snownee** [comment]
seems they are using anvil while executing reload command?

**Comment by TheButterbrotMan** [comment]
No. They open it, put item in and it crashes.

**Comment by TheButterbrotMan** [comment]
Can i do anything to help you fix this bug fast?
