### ISSUE TITLE
Suggestion: Set item on fire if lava is item entity. 

### ISSUE THREAD

**Issue by ghost** [Snownee/Lychee#22]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.1.2

### Modloader version

Forge - 40.1.47

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Set item on fire if lava is 1 block away in cardinal direction.. (i.e. if item is thrown on a cobblestone block and to north, south, east, or west is lava the item is set on fire triggering fire, triggering Item Entity Burning recipe)

**Comment by Snownee** [comment]
i don't think it is a good idea. just imagine someone dying near lava

**Comment by ghost** [comment]
What if you added a special effect to make burning items bounce on lava? Reason why I’m asking is I want something similar to the effect in lavablock modpack. Where item can be thrown into lava to create a new item but issue lies in the new item getting burned up as soon as it’s crafted.
