### ISSUE TITLE
Crash when trying to view lightning channeling recipes in jei

### ISSUE THREAD

**Issue by ElysiaSilly** [Snownee/Lychee#26]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.3.0

### Modloader version

40.1.73

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

No crash logs get generated

### Issue description

When using R on an item that has a lightning channeling recipe the world crashes and gets stuck on the saving world screen
nothing shows up in the console either, just it stating that the player has left the world

**Comment by Snownee** [comment]
what is your recipe?
what is your jei's version
can you reproduce it with jei 9.7.0.195?
