### ISSUE TITLE
Suggestion: Condition/field for whether or not a player is sneaking

### ISSUE THREAD

**Issue by vertexcubed** [Snownee/Lychee#27]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.4.2

### Modloader version

40.1.68

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

For the block interacting and block clicking recipe types it'd be nice if there was a field to check if the player is sneaking. This could be done as either a field or a context condition.

**Comment by Shadowdragon019** [comment]
I agree, as I also need this
