### ISSUE TITLE
[Bug] block_clicking works by left-clicking with axe

### ISSUE THREAD

**Issue by MSandro** [Snownee/Lychee#28]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

2.6.0

### Modloader version

0.14.9

### Modpack info

Sky FABRICation 3 

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

block_clicking should work by right-clicking if I understand it correctly.
but if I join my world it works with left clicking.

```
{
   "type": "lychee:block_clicking",
   "item_in": {
       "tag": "c:axes"
   },
   "block_in": "minecraft:bamboo",
   "post": [
       {
           "type": "drop_item",
           "item": "twigs:bamboo_leaves",
           "contextual": {
               "type": "chance",
               "chance": 0.5
           }
       },
       {
           "type": "place",
           "block": "twigs:stripped_bamboo"
       },
       {
           "type": "damage_item"
       }
   ]
}

```

**Comment by Snownee** [comment]
use "lychee:block_interacting"

https://lycheetweaker.readthedocs.io/en/latest/recipe/#use-item-on-a-block
