### ISSUE TITLE
[Suggestion] Contextual Condition - Difficult Check

### ISSUE THREAD

**Issue by Shadowdragon019** [Snownee/Lychee#32]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

2.8.1

### Modloader version

Loader: 0.14.9, API: 0.59.0

### Modpack info

n/a

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

A condition to check the player's gamemode.
This would be useful for things like items not dropping in creative/not damaging tools.

Survival: 'survival', 's', 0
Creative: 'creative', 'c', 1
Adventure: 'adventure', 'a', 2
Spectator: 'spectator', 's', 3

**Comment by Snownee** [comment]
solved in discord
