### ISSUE TITLE
Contextual Condition requirement

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Snownee/Lychee#34]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.2.0

### Modloader version

forge 43.1.57

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Can be added shift requirement to Contextual Condition ?

**Comment by Snownee** [comment]
already added

**Comment by AlleCraft-alterego** [comment]
on the wiki i don't have see this condition

**Comment by Snownee** [comment]
https://lycheetweaker.readthedocs.io/en/latest/contextual-condition/#requires-entity-crouching-is_sneaking
