### ISSUE TITLE
Throwing items into flowing fluid still works.

### ISSUE THREAD

**Issue by Alan-Yan-CanMeng** [Snownee/Lychee#35]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.9.0

### Modloader version

Forge:40.1.87

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

type:item_inside
Throwing items into flowing fluid still works.

**Comment by Alan-Yan-CanMeng** [comment]
I just want the item to be thrown into the fluid source to take effect.

**Comment by Snownee** [comment]
https://lycheetweaker.readthedocs.io/en/latest/general-types/#statepropertiespredicate

**Comment by Alan-Yan-CanMeng** [comment]
Thank you,My bad.
