### ISSUE TITLE
Unknown Recipe Category Warnings 

### ISSUE THREAD

**Issue by kingkuys2123** [Snownee/Lychee#36]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.4.0

### Modloader version

Loader 0.14.11 + API 0.71.0

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

Can these warnings be ignored?

> [13:54:33] [Render thread/WARN]: Unknown recipe category: lychee:block_interacting/lychee:expanded_delight/sugar_cane
> [13:54:33] [Render thread/WARN]: Unknown recipe category: lychee:block_interacting/lychee:expanded_delight/ground_cinnamon
> [13:54:33] [Render thread/WARN]: Unknown recipe category: lychee:block_interacting/lychee:expanded_delight/salt

**Comment by Snownee** [comment]
You can ignore them. There doesn't seem to be an easy way to hide them

**Comment by kingkuys2123** [comment]
I am new to java programming and looking to create a mod soon and looking at source codes to learn even more. Is it possible for you @Snownee doing it the same way like Farmer's Delight did to suppress their recipe warnings? Correct me because I might be wrong :)

https://github.com/newhoryzon/farmers-delight-fabric/commit/43c1e6ce061fc7cdd9a08ca2444e98b232235ca0

```
    @Override
    public boolean isIgnoredInRecipeBook() {
        return true;
    }
```

**Comment by kingkuys2123** [comment]
Oh wait, those warnings won't show up anymore after I updated Fabric Loader and Fabric API to the latest versions, they must've done something 😮 can you confirm this on your end?
