### ISSUE TITLE
[Suggestion] EMI Support for Fabric Version

### ISSUE THREAD

**Issue by Noobulus** [Snownee/Lychee#37]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.4.0

### Modloader version

Quilt 1.17.8 / QFAPI 4.0.0-beta.25+0.70.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

[EMI](https://modrinth.com/mod/emi) is an up-and-coming recipe viewer (much like JEI/REI) currently supporting the Fabric mod loader. Support for this recipe viewer would be a wonderful feature to have in Lychee.

The API docs for EMI are located here: [https://github.com/emilyploszaj/emi/wiki/Getting-Started-Guide](https://github.com/emilyploszaj/emi/wiki/Getting-Started-Guide).

**Comment by SettingDust** [comment]
![图片](https://github.com/Snownee/Lychee/assets/19922286/b287e50b-87ea-4ff2-995a-31fe57a643b2)
![图片](https://github.com/Snownee/Lychee/assets/19922286/be465a39-075b-431f-a701-c20a705d0de8)

working fine with EMI JEI compat.
