### ISSUE TITLE
Advanced Shaped Crafting crash on stack recipe crafting

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Snownee/Lychee#38]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.5.0

### Modloader version

forge 43.2.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://user-images.githubusercontent.com/72225590/211671871-7bc6a280-b2d1-47a5-bb3f-d480ebb44839.png)
[latest.log](https://github.com/Snownee/Lychee/files/10387162/latest.log)
[lychee_crafting_recipe.zip](https://github.com/Snownee/Lychee/files/10387183/lychee_crafting_recipe.zip)

the recipe work, only if use only 1 click, if i use shift for craft a stack.... crash the game, and.... can possible add shapeless crafting of lychee ?

**Comment by Snownee** [comment]
Can you reproduce it without Fast Workbench?

**Comment by AlleCraft-alterego** [comment]
Mh... without Fast Workbench the recipe work, can be possible set command or any post only 1 on stack recipe ?

**Comment by Snownee** [comment]
It is not possible. I think it is a bug from Fast Workbench because its behavior is inconsistent with vanilla

**Comment by AlleCraft-alterego** [comment]
ok, thanks, i tested the recipe with structuredcrafting... and work, don't make sound (in my recipe there is a command with anvil sound) but is very slow to craft this recipe

**Comment by AlleCraft-alterego** [comment]
and with anthillinside don't make sound but the anvil is outputed

**Comment by Snownee** [comment]
I released an update that will probably fix the issue
