### ISSUE TITLE
[Suggestion] several items from smelting

### ISSUE THREAD

**Issue by diznover** [Snownee/Lychee#39]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.6.1

### Modloader version

Fabric: Loader 0.14.12 API 0.72.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

In regular minecraft:smelting/smoking/blasting it is impossible to get more than one item after processing, can you please add such an opportunity?

**Comment by Snownee** [comment]
I think this is out of the scope of what this mod does. so, no
