### ISSUE TITLE
I can't log in to the server with this mod

### ISSUE THREAD

**Issue by diznover** [Snownee/Lychee#40]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.6.2

### Modloader version

Fabric: Loader 0.14.12 API 0.70.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Your mod is installed on the server, and when I try to log in to the server, I get an error, but when I log in to the server with your mod on the client there is no error, so the mod is not server-side only?

Internal Exception: io.netty handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer lychee:item_inside

**Comment by Snownee** [comment]
It is not recommended, but if you do want to do so, IIRC you need this: https://github.com/TheEpicBlock/PolyMc

**Comment by diznover** [comment]
Thank you, it works, I can log on to the server and use the mod's capabilities, in part, recipes where tags are used do not work, but those recipes that indicate only items work, but you didn't recommend this method, so there's nothing to complain about. Although your mod would fit perfectly into server-side only, and those who at least want to see recipes in the JEI/REI could put it to themselves optionally
