### ISSUE TITLE
Mixin error on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [Snownee/Lychee#42]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

3.9.1

### Modloader version

Quilt 0.18.5

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/tbZfCVbq

### Issue description

Crashing while trying to start up MC gives me this. It seems to be a mixin issue with Lychee.

**Comment by Sunconure11** [comment]
Oh, didn't notice something else in the error. Will send to the appropriate dev too.

**Comment by Snownee** [comment]
No, it simply cannot work with Quilt currently
