### ISSUE TITLE
Game crash with mana and artifice

### ISSUE THREAD

**Issue by Gogo08190** [Snownee/Lychee#45]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.9.1

### Modloader version

Forge-40.2.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/eRUf2eb9

### Issue description

When I open the mana and artifice codex there is nothing written in it but an arrow. 
When I click on this arrow to turn the page my game crashes
![image](https://user-images.githubusercontent.com/41335079/236380696-31d905db-3a28-42a1-af87-2f809cd31671.png)

**Comment by Snownee** [comment]
You can disable the original recipe and use a new id for the item. If it does not work, please report it to the mana and artifice devs

**Comment by Gogo08190** [comment]
What do you call original recipe?

**Comment by Snownee** [comment]
I don't know. Didn't you tweak the mana and artifice's recipe?

**Comment by Gogo08190** [comment]
Yes I changed the recipe, but now I give me the book from JEI !
If you read the crash report it talks about the Lychee mod
