### ISSUE TITLE
Click Machine sneak not being detected

### ISSUE THREAD

**Issue by Electrolyte220** [Snownee/Lychee#46]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.10.1

### Modloader version

Forge 43.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Due how click machine sets up their fake player, the way Lychee detects the player shifting is not applicable.
All that's needed to fix this is a check for isShiftKeyDown(), as that's how click machine assigns sneaking to their fake player.

**Comment by 800020h** [comment]
it can't _only_ check for isShiftKeyDown() because not everyone sneaks with shift

**Comment by Electrolyte220** [comment]
True, so instead you can have a check for either: 
`return ctx.getParam(LootContextParams.THIS_ENTITY).isCrouching() || ctx.getParam(LootContextParams.THIS_ENTITY).isShiftKeyDown() ? times : 0;` instead of just 
`return ctx.getParam(LootContextParams.THIS_ENTITY).isCrouching() ? times : 0;` and that seemed to fix it when I tested it.
