### ISSUE TITLE
[Suggestion]Make the gamerule doLimitedCrafting available for lychee recipes

### ISSUE THREAD

**Issue by openforge233** [Snownee/Lychee#47]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.11

### Modloader version

Forge:43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When I'm making my own modpack with gamestages,tons of recipes are based on lychee.Because of the awful wiki of recipes stage mod,I have to use the vanilla  gamerule doLimitedCrafting.I give all players all recipes and take the recipes I need to take in my load.mcfunction while rewarding the recipes I take in advancements.When it comes to lychee recipes,it fails.I hope my way to deal with stage recipes can works on lychee recipes.

**Comment by Snownee** [comment]
你想实现什么具体功能？

**Comment by openforge233** [comment]
> 你想实现什么具体功能？
借助原版的doLimitedCrafting游戏规则阻止lychee配方
即如果我有一个lychee配方，我希望当我启用doLimitedCrafting规则时，被剥夺了这个配方（/recipe take 命令）的玩家不能执行这个配方

**Comment by Snownee** [comment]
我是说具体的配方。你还是上discord和我说吧
