### ISSUE TITLE
Click machines cannot do Lychee recipes (Block Clicking for example)

### ISSUE THREAD

**Issue by Leclowndu93150** [Snownee/Lychee#48]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.11

### Modloader version

Latest

### Modpack info

custom modpack

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://github.com/Snownee/Lychee/assets/73310949/4bbe68d9-ba63-4ad3-bbba-cdd231917268)
It does the recipe once then stops

**Comment by Leclowndu93150** [comment]
{
        "type": "lychee:block_clicking",
        "item_in": {
            "item": "minecraft:air"
        },
        "block_in": "chipped:tiled_blue_stained_glass",
        "post": [{
                "type": "drop_item",
                "item": "vinery:chenet_wine"
            },
            {
                "type": "add_item_cooldown",
                "s": "0.25"
            }
        ],

    }

**Comment by Snownee** [comment]
Click Machine's fake player does not support item cooldowns. Avoid using it or report to Click Machine

**Comment by Leclowndu93150** [comment]
ty
