### ISSUE TITLE
Use KubeJS Server scripts instead of Startup scripts

### ISSUE THREAD

**Issue by slava110** [Snownee/Lychee#51]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.14.0

### Modloader version

Forge 43.2.21

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It isn't convenient from modpack maker's perspective to reload minecraft after changing a few lines of code in KubeJS custom action or condition. Instead of using `Startup` scripts `Server` scripts could be used for KubeJS integration. It will allow modpack makers to make changes and test them right after `reload` command (instead of restarting the whole game).

**Comment by Snownee** [comment]
use `/kubejs reload startup_scripts`

**Comment by slava110** [comment]
It doesn't reload Lychee custom actions defined in my script

**Comment by Snownee** [comment]
does it work if you run `/reload` then?

**Comment by slava110** [comment]
~~No it doesn't. `/reload` only reloads server scripts. Currently Lychee requires full client restart to apply changes~~

**Comment by slava110** [comment]
Oh, I see. I need to use **both** `/kubejs reload startup_scripts` and `/reload`. That's weird. Is it possible to just use Server Scripts in the future?

**Comment by Snownee** [comment]
probably not. because some part of the code will be executed on the client side (testInTooltipsFunc)

**Comment by slava110** [comment]
What if `testInTooltips` will be on client side then? Something like `LycheeEvents.customConditionTooltip(String conditionId, ...)`.
And `customAction`, `customCondition` will be used on server side.

**Comment by Snownee** [comment]
not only that, the `event.condition.testFunc` can also be executed on the client side
