### ISSUE TITLE
Waterlogged in block state does not work.

### ISSUE THREAD

**Issue by tsubfak13** [Snownee/Lychee#52]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.14.0

### Modloader version

forge43.2.1

### Modpack info

https://legacy.curseforge.com/minecraft/modpacks/gregtronix-revoluton

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

At the very beginning, I wanted to place a block (stone hand) from eidolon, but it turned out that the waterlogged of the block was true after it was placed.
Then I tested vanlia slabs and found that 'waterlogged' in block state didn't work.

**Comment by Snownee** [comment]
what do you mean? post your minimal reproducible example that contains only vanilla items and blocks, please.
