### ISSUE TITLE
Bug: ClientLevel cannot be cast to class ServerLevel

### ISSUE THREAD

**Issue by firemaster1294** [Snownee/Lychee#56]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

2.9.1

### Modloader version

Forge 40.2.10

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/09gsddkW

### Issue description

When right clicking on a plank with a stick, per a defined recipe that was created using KubeJS, I receive the error that ClientLevel cannot be cast to ServerLevel.

The associated crafting recipe can be found here: https://pastebin.com/fxeMqRp3

**Comment by Snownee** [comment]
Can you use `location` to check for blocks instead?

**Comment by firemaster1294** [comment]
location works instead :) thanks!
