### ISSUE TITLE
Recipes not working with modded fluids

### ISSUE THREAD

**Issue by benbenlaw** [Snownee/Lychee#58]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

5.0.5

### Modloader version

27.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Modded fluids dont seem to work with recipes. Tested dripstone and in block

**Comment by Snownee** [comment]
use jade to see the real id

https://discord.com/channels/252384449042317313/1023515988370665562/1126749852760559647
