### ISSUE TITLE
JEI compact causes crash when attempting to view recipe of certain items

### ISSUE THREAD

**Issue by Shadowdragon019** [Snownee/Lychee#6]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

1.5.2

### Modloader version

39.0.66

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Shadowdragon019/0d44d8985f98db8149de7ef73d1f9df2

### Issue description

When you attempt to view the recipe (pressing R) of certain items causes a crash, I've tried this with 2 enchanted books, a spawner, random items, tools/armor, spawn eggs. The only things that cause a crash were the spawner, spawn eggs, & enchanted books.

Video of bug - https://www.youtube.com/watch?v=CEbSyh0T5Zg&ab_channel=Wolfboycoolkid

**Comment by Snownee** [comment]
https://github.com/mezz/JustEnoughItems/issues/2696
