### ISSUE TITLE
Suggestion - Lightning Channeling recipes for mobs

### ISSUE THREAD

**Issue by anoomolu** [Snownee/Lychee#60]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

5.0.7

### Modloader version

Fabric Loader: 0.14.24 / API: 0.90.7

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hi! Lychee's been working great for me, thank you for making such a useful tool for modpack developers.

I wanted to request another recipe type - lightning channeling to transform mobs. Similar to how lightning striking a villager makes it a witch, I was wondering if it'd be possible to extend this to other mobs. My use case is pufferfish -> guardian and guardian -> elder guardian when struck with lightning, since I'm working with a skyblock/superflat world. Other mods have this specific interaction like Carpet, but they are not data-driven.

Thanks for taking the time to read this over.

**Comment by Snownee** [comment]
This should already be possible with the following recipe:

```json
{
  "type": "lychee:lightning_channeling",
  "post": [
    {
      "type": "execute",
      "command": "execute as @e[type=minecraft:pufferfish,distance=..5] at @s run summon minecraft:guardian"
    },
    {
      "type": "execute",
      "command": "execute as @e[type=minecraft:pufferfish,distance=..5] run tp ~ ~-1000 ~"
    }
  ]
}
```

But the problem is the health value of the pufferfish is too low to withstand a lightning strike. Next, we will add an entity type tag to allow users to mark entities as lightning-resistant. @SettingDust
