### ISSUE TITLE
Contextual condition checks are run in the wrong position depending on the block face

### ISSUE THREAD

**Issue by ghost** [Snownee/Lychee#8]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

1.6.1

### Modloader version

39.0.85

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

I'm trying to make a block interaction recipe possible only if there is no log below the targeted block. This is possible with a contextual condition, `execute`. There is one problem though. The command is not run exactly where to block is and this results in weird behaviour.

Below is a video demonstration and the recipe file that I'm using.

Demonstration (play it with sound enabled):

https://user-images.githubusercontent.com/98822450/155847859-5a4051ca-faed-4054-a6cc-7998dfaceba6.mp4

Recipe file:

```json
{
	"type": "lychee:block_interacting",
	"item_in": {
		"item": "minecraft:iron_axe"
	},
	"block_in": "minecraft:stripped_oak_log",
	"post": [
		{
			"type": "prevent_default"
		},
		{
			"type": "execute",
			"command": "playsound minecraft:entity.experience_orb.pickup block @a",
			"contextual": {
				"type": "execute",
				"command": "execute unless block ~ ~-1 ~ minecraft:oak_log"
			}
		}
	]
}
```

**Comment by Snownee** [comment]
I will fix this tomorrow. Have you tried using location check? That one will run faster

https://lycheetweaker.readthedocs.io/en/latest/contextual-condition/#location-check-location

**Comment by ghost** [comment]
I didn't realise I could use location check. I should definitely be using that instead. Thanks for telling me.
