### ISSUE TITLE
[SUGGESTION] Grindstone crafting recipes

### ISSUE THREAD

**Issue by Warhand** [Snownee/Lychee#81]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

5.1.12

### Modloader version

Forge 47.2.17

### Modpack info

Currently developing a vanilla+ modpack, and this functionality would help

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I feel like adding simple grindstone recipes would complement anvil recipes quite well. The main usecase I can think of would be allowing packdevs to create recipes where users can quickly and cheaply repair their tools, at the cost of not retaining enchantments or NBT data.

If possible, it would be nice to have it remove enchantments, while retaining custom names or other unique NBT data.

It would be helpful to be able to control details like output durability, such as maybe taking the durability of an input item and then adding a certain value to it, then applying it to the output.

Should play the grindstone sound when the recipe is used, similar to anvil recipes.

**Comment by Snownee** [comment]
You can already implement this using an anvil recipe. And I have no plans to add new recipe types in the near future, so maybe you should try anvil crafting

**Comment by Warhand** [comment]
Anvil crafting would not fit my usecase here, as part of the goal is to use something cheaper than an anvil, so its more viable in early survival. However I understand if you don't plan to add any new recipe types.
