### ISSUE TITLE
[BUG] Crash when used with mods that customize Mekanism gas

### ISSUE THREAD

**Issue by SpCoGov** [Snownee/Lychee#83]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

3.15.1

### Modloader version

Forge 43.3.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/SpCoGov/8c5748d41e9cbc327bbb67bad7973065

### Issue description

This is the output with only relevant mods installed: https://gist.github.com/SpCoGov/283762cc3303c3a1395b8cb5d6e0956c

**Comment by Snownee** [comment]
please send the `latest.log`

**Comment by SpCoGov** [comment]
> [https://gist.github.com](https://gist.github.com/SpCoGov/283762cc3303c3a1395b8cb5d6e0956c)

https://gist.github.com/SpCoGov/25a51c97ae05bc0c5f9272a06723a868

**Comment by SpCoGov** [comment]
> please send the `latest.log`

https://gist.github.com/SpCoGov/25a51c97ae05bc0c5f9272a06723a868

**Comment by Snownee** [comment]
please provide the log and the mod list that with only the relevant mods you mentioned

**Comment by SpCoGov** [comment]
> please provide the log and the mod list that with only the relevant mods you mentioned

https://gist.github.com/SpCoGov/0e0a4a06041c3e8a271a51ef6c65c3bd

**Comment by SpCoGov** [comment]
> please provide the log and the mod list that with only the relevant mods you mentioned

This mod was written by myself, he just registered a few gases. When it starts alone there is no problem, but when started with Lychee it crashes

**Comment by Snownee** [comment]
why is it a bug in Lychee and not in your mod? I don't even know what you've done.

**Comment by SpCoGov** [comment]
> why is it a bug in Lychee and not in your mod? I don't even know what you've done.

because the logs look like Lychee's bug

**Comment by Snownee** [comment]
That is 100% your own business. And I still remember you, the guy who is good at "imitating" and "backing up"

**Comment by SpCoGov** [comment]
> That is 100% your own business. And I still remember you, the guy who is good at "imitating" and "backing up"

thank you for remembering me. By the way, I saw that MekanismGenerators uses "register", but I use "createAndRegister", which should be the problem.

**Comment by SettingDust** [comment]
Looks like you are using obfed lychee jar in dev env. You need deobf I think
