### ISSUE TITLE
Untranslatable character in REI when drop_item has a variable count

### ISSUE THREAD

**Issue by pskfyi** [Snownee/Lychee#84]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

5.1.12

### Modloader version

Forge 47.2.21

### Issue description

The character after "Ash" is not in `assets/lang/en_us.json` and so cannot be translated on my end via a resource pack.

## REI

<img width="765" alt="Screenshot 2024-05-12 at 11 22 54 PM" src="https://github.com/Snownee/Lychee/assets/47710574/9ab710d8-c7a7-4750-bcbb-0a8eb0577b43">

## Recipe

```json
{
  "type": "lychee:item_burning",
  "ghost": true,
  "item_in": { "tag": "logs_that_burn" },
  "post": {
    "type": "random",
    "rolls": {
      "min": 1,
      "max": 4
    },
    "entries": [
      {
        "type": "drop_item",
        "item": "supplementaries:ash"
      }
    ]
  }
}
```

**Comment by Snownee** [comment]
send your `latest.log` and don't delete the form please

**Comment by Snownee** [comment]
Never mind. No need anymore.

**Comment by Snownee** [comment]
I don't know what happened, but it's fixed now

**Comment by pskfyi** [comment]
Thank you, I can confirm it's fixed after downloading the latest update.

> send your `latest.log` and don't delete the form please

Because I did not consider this a bug, I did not think the log was required, but I will keep this in mind in the future. Sorry about this.
